# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: dependecies
        run: sudo apt install python3 python3-pip python3-dev && curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable

      # Runs a set of commands using the runners shell
      - name: pip
        run: pip3 install setuptools wheel setuptools-rust
      
      - name: compile
        run: python3 setup.py install --user
      - name: test
        run: mkdir test && cd test && echo "import ipaddr; print(ipaddr.getip())" > test.py && python3 test.py
